# Customização do dockerfile para gerar uma imagem no portainer
# Esta imagem atualizado do Python com o Oracle Instant cliente
# será base para o próximo dockerfile com a aplicação
# Nesta imagem já foi instalado o ORACLE, unzip, cron, wget, git
# Nome:	python_oracle19-8:3.13-build
# ====================================================================

FROM python:3.13.0b3
LABEL maintainer="Aquiles Rodrigues"

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y libaio1 nano zip unzip cron wget git iputils-ping traceroute openssh-server

WORKDIR /opt/oracle

RUN wget \ 
    https://download.oracle.com/otn_software/linux/instantclient/19800/instantclient-basic-linux.x64-19.8.0.0.0dbru.zip && \
    wget https://download.oracle.com/otn_software/linux/instantclient/19800/instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip && \
	unzip instantclient-basic-linux.x64-19.8.0.0.0dbru.zip -d /opt/oracle && \
    unzip instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip -d /opt/oracle/ && \
	rm -f instantclient-basic-linux.x64-19.8.0.0.0dbru.zip && \
    rm -f instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip


RUN cd /opt/oracle/instantclient_19_8 && rm -f *jdbc* *occi* *mysql* *README *jar \
    uidrvci genezi adrci

RUN echo /opt/oracle/instantclient_19_8 > /etc/ld.so.conf.d/oracle-instantclient.conf && \
    ldconfig

# Set the working directory to /app
WORKDIR /app