version: "3.8"

services:
  mariadb-server:
    container_name: mariadb-server
    image: mariadb:11.1.2-jammy
    restart: always
    env_file:
      - "/dados/docker/environment/mariadb/server.env"
    volumes:
      - "/dados/docker/persistent/mariadb/data:/var/lib/mysql/data/:rw"
      - "/dados/docker/persistent/mariadb/logs:/var/lib/mysql/logs/"
      - "/dados/docker/persistent/mariadb/conf.d:/etc/mysql/conf.d"
      - "/etc/localtime:/etc/localtime:ro"
      #     - dbsocket:/var/run/mysqld/
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
      # ou substituir por este --collation-server=utf8mb4_bin
    networks:
      - network-chur
    ports:
      - "3306:3306"

  ## POSTGRES SERVER #################################
  postgres-server:
    container_name: postgres-server
    image: postgres:13-bullseye
    restart: unless-stopped
    env_file:
      - "/dados/docker/environment/postgresql/tie-in.env"
    volumes:
      - "/dados/docker/persistent/postgresql/conf.d/:/etc/postgresql/conf.d"
      - "/dados/docker/persistent/postgresql/data:/var/lib/postgresql/data/:rw"
      - "/dados/docker/persistent/postgresql/logs:/var/lib/postgresql/logs/"
      - "/dados/docker/persistent/postgresql/conf.d:/etc/postgresql/conf.d"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - network-chur
    ports:
      - "5432:5432"

  ## ZABBIX INFRA #####################################
  #####################################################

  ## ZABBIX POSTGRES ##################################
  zabbix-postgres:
    container_name: zabbix-postgres
    image: postgres:13-bullseye
    env_file:
      - "/dados/docker/environment/zabbix/sgbd/tie-in.env"
    volumes:
      - "/dados/docker/persistent/postgresql/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh"
      - "/dados/docker/persistent/postgresql/data:/var/lib/postgresql/data/:rw"
      - "/dados/docker/persistent/postgresql/logs:/var/lib/postgresql/logs/"
      - "/dados/docker/persistent/postgresql/conf.d:/etc/postgresql/conf.d"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - network-chur

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql
    restart: always
    pull_policy: always
    depends_on:
      - postgres-server
    env_file:
      - "/dados/docker/environment/zabbix/sgbd/tie-in.env"
      - "/dados/docker/environment/zabbix/server/server.env"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - /dados/docker/persistent/zabbix/usr/lib/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /dados/docker/persistent/zabbix/usr/lib/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /dados/docker/persistent/zabbix/var/lib/dbscripts:/var/lib/zabbix/dbscripts:ro
      - /dados/docker/persistent/zabbix/var/lib/export:/var/lib/zabbix/export:rw
      - /dados/docker/persistent/zabbix/var/lib/modules/:/var/lib/zabbix/modules:ro
      - /dados/docker/persistent/zabbix/var/lib/enc:/var/lib/zabbix/enc:ro
      - /dados/docker/persistent/zabbix/var/lib/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /dados/docker/persistent/zabbix/var/lib/mibs:/var/lib/zabbix/mibs:ro
      - /dados/docker/persistent/zabbix/var/lib/snmptraps:/var/lib/zabbix/snmptraps:rw
    ports:
      - "10051:10051"
    networks:
      - network-chur
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "ubuntu"

  ## ZABBIX WEB #################################
  #################################################
  zabbix-web-nginx-mysql:
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-trunk
    restart: always
    pull_policy: always
    env_file:
      - "/dados/docker/environment/zabbix/sgbd/tie-in.env"
      # /etc/ssl/nginx
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=mariadb-server
    depends_on:
      - mariadb-server
      - zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dados/docker/persistent/zabbix/var/lib/modules/:/var/lib/zabbix/modules:ro
      - /dados/docker/persistent/nginx/etc/ssl:/etc/ssl/nginx:ro
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - network-chur
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with  MySQL  database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "ubuntu"

  ## ZABBIX SNMP #################################
  #################################################
  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:ubuntu-6.4-latest
    restart: unless-stopped
    ports:
      - "162:1162/udp"
    volumes:
      - /dados/docker/persistent/zabbix/var/lib/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /dados/docker/persistent/zabbix/var/lib/mibs:/var/lib/zabbix/mibs:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
    networks:
      - network-chur
    labels:
      com.zabbix.description: "Zabbix snmptraps"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "snmptraps"
      com.zabbix.os: "ubuntu"

  zabbix-agent:
    container_name: zabbix-agent2
    image: zabbix/zabbix-agent2
    user: root
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
      - /dados/docker/persistent/zabbix/etc/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - /dados/docker/persistent/zabbix/var/lib/enc:/var/lib/zabbix/enc:ro
      - /dados/docker/persistent/zabbix/var/lib/modules:/var/lib/zabbix/modules:rw
      - /dados/docker/persistent/zabbix/var/lib/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    ports:
      - "10050:10050"
    env_file:
      - "/dados/docker/environment/zabbix/agent/agent.env"
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - DB_SERVER_HOST=mariadb-server
    networks:
      - network-chur
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "ubuntu"

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mariadb-server
      - zabbix-server
    networks:
      - network-chur
    labels:
      com.grafana.description: "Grafana Dashboard"
      com.grafana.company: "Grafana LLC"
      com.grafana.component: "grafana"
      com.grafana.os: "ubuntu"
# ===================================================

#  web:
#    image: nginx:latest
#    container_name: nginx-php
#    networks:
#      - network-chur
#    depends_on:
#      - php
#    ports:
#      - "80:80"
#    volumes:
#      - "/dados/docker/environment/nginx/docker.sock:/tmp/docker.sock:ro"
#      - "/dados/docker/environment/nginx/php-fpm/default.conf:/etc/nginx/conf.d/default.conf"
#      - "/dados/docker/persistent/www/html:/var/www/html"
#  php:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: php-fpm
#    restart: always
#    container_name: php-fpm
#    networks:
#      - network-chur
#    volumes:
#      - "/dados/docker/persistent/www/html:/var/www/html"

#  myadmin:
#    image: phpmyadmin:5.2.1-fpm
#    container_name: phpmyadmin
#    depends_on:
#      - mariadb-server
#    environment:
#      - PMA_HOST = mariadb-server
#    ports:
#      - 8080:80

############################################
networks:
  network-chur:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"
