version: "3.5"

services:
  mysql-server:
    image: mysql:8.0.34
    container_name: mysql-server
    restart: always
    networks:
      - network-chur
    ports:
      - "3306:3306"
    env_file:
      - "/dados/docker/environment/mysql/sgbd/mysql.env"
    volumes:
      - "/dados/docker/persistent/mysql/data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"

  ####### ZABBIX create Database ##########
  zabbix-mysql:
    container_name: zabbix-mysql
    image: mysql:8.0.34
    ports:
      - "3301:3306"
    depends_on:
      - mysql-server
    networks:
      - network-chur
    env_file:
      - "/dados/docker/environment/zabbix/sgbd/mysql.env"
    volumes:
      - "/dados/docker/persistent/mysql/data:/var/lib/mysql"
  ####### ZABBIX INFRA ##########
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql
    depends_on:
      - mysql-server
      - zabbix-mysql
    networks:
      - network-chur
    links:
      - mysql-server
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - "/dados/docker/environment/zabbix/server/alertscripts:/usr/lib/zabbix/alertscripts"
      # /etc/zabbix/zabbix_server.conf
    env_file:
      - "/dados/docker/environment/zabbix/sgbd/mysql.env"

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-mysql
    networks:
      - network-chur
    links:
      - mysql-server
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    env_file:
      - "/dados/docker/environment/zabbix/sgbd/mysql.env"
    environment:
      - ZBX_SERVER_HOST="127.0.0.1"
      - DB_SERVER_HOST="127.0.0.1"
    depends_on:
      - mysql-server
      - zabbix-mysql

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-chur
    links:
      - mysql-server
      - zabbix-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql-server
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2
    user: root
    networks:
      - network-chur
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST="127.0.0.1,localhost"

# ===================================================

#  web:
#    image: nginx:latest
#    container_name: nginx-php
#    networks:
#      - network-chur
#    depends_on:
#      - php
#    ports:
#      - "80:80"
#    volumes:
#      - "/dados/docker/environment/nginx/docker.sock:/tmp/docker.sock:ro"
#      - "/dados/docker/environment/nginx/php-fpm/default.conf:/etc/nginx/conf.d/default.conf"
#      - "/dados/docker/persistent/www/html:/var/www/html"
#  php:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: php-fpm
#    restart: always
#    container_name: php-fpm
#    networks:
#      - network-chur
#    volumes:
#      - "/dados/docker/persistent/www/html:/var/www/html"

#  myadmin:
#    image: phpmyadmin:5.2.1-fpm
#    container_name: phpmyadmin
#    depends_on:
#      - mysql-server
#    environment:
#      - PMA_HOST = mysql-server
#    ports:
#      - 8080:80

############################################
networks:
  network-chur:
    driver: bridge
