version: "3.8"

services:
  mysql-server:
    container_name: mysql-server
    image: mysql:8.0.34
    restart: always
    env_file:
      - "/dados/docker/environment/mysql/sgbd/mysql.env"
    volumes:
      - "/dados/docker/persistent/mysql/data:/var/lib/mysql:rw"
      - "/etc/localtime:/etc/localtime:ro"
      #     - dbsocket:/var/run/mysqld/
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
      # ou substituir por este --collation-server=utf8mb4_bin
    networks:
      rede-chur:
        ipv4_address: 10.200.0.10
    ports:
      - "3306:3306"

  ####### ZABBIX INFRA ##########
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql
    restart: always
    pull_policy: always
    depends_on:
      - mysql-server
    env_file:
      - "/dados/docker/environment/zabbix/sgbd/mysql.env"
      - "/dados/docker/environment/zabbix/server/server.env"
    environment:
      - DB_SERVER_HOST=10.200.0.10
      - DB_SERVER_PORT=3306
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - /dados/docker/persistent/zabbix/usr/lib/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /dados/docker/persistent/zabbix/usr/lib/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /dados/docker/persistent/zabbix/var/lib/dbscripts:/var/lib/zabbix/dbscripts:ro
      - /dados/docker/persistent/zabbix/var/lib/export:/var/lib/zabbix/export:rw
      - /dados/docker/persistent/zabbix/var/lib/modules/:/var/lib/zabbix/modules:ro
      - /dados/docker/persistent/zabbix/var/lib/enc:/var/lib/zabbix/enc:ro
      - /dados/docker/persistent/zabbix/var/lib/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /dados/docker/persistent/zabbix/var/lib/mibs:/var/lib/zabbix/mibs:ro
      - /dados/docker/persistent/zabbix/var/lib/snmptraps:/var/lib/zabbix/snmptraps:rw
    ports:
      - "10051:10051"
    networks:
      rede-chur:
        ipv4_address: 10.200.0.7
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "ubuntu"

  zabbix-web-nginx-mysql:
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-nginx-mysql:trunk-ubuntu
    restart: always
    pull_policy: always
    env_file:
      - "/dados/docker/environment/zabbix/sgbd/mysql.env"
    environment:
      - ZBX_SERVER_HOST="10.200.0.7"
      - DB_SERVER_HOST="10.200.0.10"
    depends_on:
      - mysql-server
      - zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dados/docker/persistent/zabbix/var/lib/modules/:/var/lib/zabbix/modules:ro
      - /dados/docker/persistent/nginx/etc/ssl:/etc/ssl/nginx:ro
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      rede-chur:
        ipv4_address: 10.200.0.8
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with  MySQL  database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "ubuntu"

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:ubuntu-6.4-latest
    profiles:
      - full
      - all
    ports:
      - "162:1162/udp"
    volumes:
      - /dados/docker/persistent/zabbix/var/lib/snmptraps:/var/lib/zabbix/snmptraps:rw
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
    networks:
      rede-chur:
        ipv4_address: 10.200.0.5
    labels:
      com.zabbix.description: "Zabbix snmptraps"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "snmptraps"
      com.zabbix.os: "ubuntu"

  zabbix-agent:
    container_name: zabbix-agent2
    image: zabbix/zabbix-agent2
    user: root
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
      - /dados/docker/persistent/zabbix/etc/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - /dados/docker/persistent/zabbix/var/lib/enc:/var/lib/zabbix/enc:ro
      - /dados/docker/persistent/zabbix/var/lib/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    ports:
      - "10050:10050"
    env_file:
      - "/dados/docker/environment/zabbix/agent/agent.env"
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST="zabbix-server,localhost"
    networks:
      rede-chur:
        ipv4_address: 10.200.0.4
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "ubuntu"

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql-server
      - zabbix-server
    networks:
      rede-chur:
        ipv4_address: 10.200.0.9
    labels:
      com.grafana.description: "Grafana Dashboard"
      com.grafana.company: "Grafana LLC"
      com.grafana.component: "grafana"
      com.grafana.os: "ubuntu"
# ===================================================

#  web:
#    image: nginx:latest
#    container_name: nginx-php
#    networks:
#      - network-chur
#    depends_on:
#      - php
#    ports:
#      - "80:80"
#    volumes:
#      - "/dados/docker/environment/nginx/docker.sock:/tmp/docker.sock:ro"
#      - "/dados/docker/environment/nginx/php-fpm/default.conf:/etc/nginx/conf.d/default.conf"
#      - "/dados/docker/persistent/www/html:/var/www/html"
#  php:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: php-fpm
#    restart: always
#    container_name: php-fpm
#    networks:
#      - network-chur
#    volumes:
#      - "/dados/docker/persistent/www/html:/var/www/html"

#  myadmin:
#    image: phpmyadmin:5.2.1-fpm
#    container_name: phpmyadmin
#    depends_on:
#      - mysql-server
#    environment:
#      - PMA_HOST = mysql-server
#    ports:
#      - 8080:80

############################################
networks:
  rede-chur:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/24
          gateway: 10.200.0.1
