# vim docker-compose.yml

version: '3.5'

services:
  web:
    image: nginx:latest
    container_name: nginx-php
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - /dados/docker/persistent/www:/var/www/html
      - /dados/docker/environment/nginx/php-fpm/default.conf:/etc/nginx/conf.d/default.conf
      
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm
    container_name: php-fpm
    volumes:
      - ./www:/var/www/html
      
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql
    volumes:
      - ./data:/var/lib/mysql
  admin:
    image: phpmyadmin/phpmyadmin
    container_name: admin
    depends_on:
      - db
    environment:
      - PMA_HOST = db
    ports:
      - 8080:80