version: "3.5"

services:
  mysql-server:
    container_name: mysql-server
    image: mysql:8.0.34
    restart: always
    env_file:
      - "/dados/docker/environment/mysql/sgbd/mysql.env"
    volumes:
      - "/dados/docker/persistent/mysql/data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    network:
      network-chur:
        ipv4_address: 10.200.0.10
    ports:
      - "3306:3306"

  ####### ZABBIX INFRA ##########
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql
    restart: always
    pull_policy: always
    depends_on:
      - mysql-server
    env_file:
      - "/dados/docker/environment/zabbix/sgbd/mysql.env"
    environment:
      - DB_SERVER_HOST=10.200.0.10
      - DB_SERVER_PORT=3306
    volumes:
      - "/dados/docker/environment/zabbix/server/alertscripts:/usr/lib/zabbix/alertscripts"
      - "/dados/docker/persistent/zabbix/server/module:/var/lib/zabbix/modules"
    network:
      network-chur:
        ipv4_address: 10.200.0.7
    ports:
      - "10051:10051"

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-mysq:trunk-ubuntu
    networks:
      - network-chur
    links:
      - mysql-server
    restart: always
    env_file:
      - "/dados/docker/environment/zabbix/sgbd/mysql.env"
    environment:
      - ZBX_SERVER_HOST="10.200.0.7"
      - DB_SERVER_HOST="10.200.0.10"
    depends_on:
      - mysql-server
      - zabbix-mysql
    network:
      network-chur:
        ipv4_address: 10.200.0.8
    ports:
      - "8080:8080"
      - "8443:8443"
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql-server
      - zabbix-server
    network:
      network-chur:
        ipv4_address: 10.200.0.11

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2
    user: root
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST="10.200.0.7,localhost"
    network:
      network-chur:
        ipv4_address: 10.200.0.12

# ===================================================

#  web:
#    image: nginx:latest
#    container_name: nginx-php
#    networks:
#      - network-chur
#    depends_on:
#      - php
#    ports:
#      - "80:80"
#    volumes:
#      - "/dados/docker/environment/nginx/docker.sock:/tmp/docker.sock:ro"
#      - "/dados/docker/environment/nginx/php-fpm/default.conf:/etc/nginx/conf.d/default.conf"
#      - "/dados/docker/persistent/www/html:/var/www/html"
#  php:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: php-fpm
#    restart: always
#    container_name: php-fpm
#    networks:
#      - network-chur
#    volumes:
#      - "/dados/docker/persistent/www/html:/var/www/html"

#  myadmin:
#    image: phpmyadmin:5.2.1-fpm
#    container_name: phpmyadmin
#    depends_on:
#      - mysql-server
#    environment:
#      - PMA_HOST = mysql-server
#    ports:
#      - 8080:80

############################################
networks:
  network-chur:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/24
          gateway: 10.200.0.1
