# Utilizando sintax da versão 2:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: "3"

services:
  ###################################
  # Container proxy-reverse (Nginx)
  ###################################
  nginx-reverse:
    image: nginx:latest
    hostname: nginx-reverse
    container_name: nginx-reverse_compose
    restart: always
    depends_on:
      - php-fpm
    networks:
      - rede-chur
    #        extra_hosts:
    #            - "gitlab.chur.com.br:10.0.1.11"
    #            - "chur.com.br:10.0.1.10"
    ports:
      - 8080:80
      - 443:443
    volumes:
      # Volume para NGINX
      - "nginx-reverse_config:/etc/nginx"
      # MAPEAR ARQUIVO CONFIGURACAO DO PHP PARA NGINX
      - "/dados/docker/environment/nginx/php-fpm.conf:/etc/nginx/conf.d/php-fpm.conf"
      # PASTA COMPARTILHADA CERTIFICADOS
      - "certificate-ssl:/etc/nginx/ssl"
      # PASTAS STATUS DO HOST NGINX
      - "/dados/docker/persistent/nginx/root:/root"
      - "/dados/docker/persistent/nginx/NGINX_cache:/tmp/NGINX_cache"
      - "/dados/docker/persistent/nginx/logs:/var/log/nginx"
        # PASTA PUBLICA ENTRE CONTAINERS
      - "docker-public:/public"
        # SINCRONIZA TIME
      - "/etc/localtime:/etc/localtime:ro"
      #- "/var/run/docker.sock:/tmp/docker.sock:ro"
    environment:
      # - NGINX_HOST=xpaco.com.br
      - NGINX_PORT=80
    volumes_from:
      - php-fpm

  ###########################
  # Container PHP
  ###########################
  php-fpm:
    build: "/dados/docker/environment/php/"
    restart: always
    hostname: php-fpm
    container_name: php-fpm_compose
    networks:
      - rede-chur
    expose:
      - 9000
    volumes:
      - "php-sites:/var/www/html"
      - "/dados/docker/environment/php/php-logging.conf:/usr/local/etc/php-fpm.d/zz-log.conf"
      - "/etc/localtime:/etc/localtime:ro"
  #
  ###########################
  # Container de banco de dados (MySQL)
  ###########################
  mariadb:
    image: mariadb:10.0
    hostname: mariadb
    container_name: mariadb_compose
    restart: always
    networks:
      - rede-chur
    ports:
      - "3306:3306"
    volumes:
      # Persistente
      - "mariadb-database:/var/lib/mysql"
      # Ambiente
      - "mariadb-conf-d:/etc/mysql/conf.d"
      - "/dados/docker/environment/mariadb/my.cnf:/etc/mysql/my.cnf"
      - "/etc/localtime:/etc/localtime:ro"
      #     - dbsocket:/var/run/mysqld/
    env_file:
      - "/dados/docker/environment/mariadb/tie-in.env"

volumes:
  php-sites:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/persistent/php/html'
  mariadb-database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/persistent/mariadb/database'
  mariadb-conf-d:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/environment/mariadb/conf.d'
  nginx-reverse_config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/persistent/nginx/'
  certificate-ssl:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/environment/ssl'    
  docker-public:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /var/docker/public
    
networks:
  rede-chur:
    driver: bridge
    ipam:
      driver: default
