version: "3.5"

services:
  web:
    image: nginx:latest
    container_name: nginx-php
    networks:
      - network-chur
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - "/dados/docker/persistent/www/html:/var/www/html"
      - "/dados/docker/environment/nginx/php-fpm/default.conf:/etc/nginx/conf.d/default.conf"
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm
    container_name: php-fpm
    networks:
      - network-chur
    volumes:
      - "/dados/docker/persistent/www/html:/var/www/html"

  sgbd-mysql:
    image: mysql:8.0.34
    container_name: mysql
    networks:
      - network-chur
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql
    volumes:
      - "/dados/docker/persistent/mysql/data:/var/lib/mysql"

  myadmin:
    image: phpmyadmin:5.2.1-fpm
    container_name: phpmyadmin
    depends_on:
      - sgbd-mysql
    environment:
      - PMA_HOST = sgbd-mysql
    ports:
      - 8080:80
networks:
  network-chur:
    driver: bridge
