version: '3.5'
services:
  database-micros:
    image: mysql:8.1.0
    restart: always
    env_file: /environment/database-micros/database.conf
    volumes:
      - '/dados/docker/persistent/mysql/data/:/var/lib/mysql'    

  web:
    image: php:7.4.12-apache-buster
    volumes:
      - /dados/docker/persistent/www:/var/www 
    ports:
      - 80:80 
    depends_on:
      - api-readers
      - api-books
  mysql:
    container_name: chur-mysql
    image: mysql:8.1.0
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;
    networks:
      - network-chur
    ports:
      - '3306:3306'
    volumes:
      - '/dados/docker/persistent/mysql/data/:/var/lib/mysql'
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=carryontech
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
      - TZ=Asia/Shanghai

networks:
  network-zabbix:
    driver: bridge

volumes:
  db_volume-books:
  db_volume-readers: