version: "3.5"

services:
  sgbd-mysql:
    image: mysql:8.0.34
    container_name: sgbd-mysql
    networks:
      - network-chur
    ports:
      - "3306:3306"
    env_file:
      - "/dados/docker/environment/mysql/sgbd/mysql.env"
    volumes:
      - "/dados/docker/persistent/mysql/data:/var/lib/mysql"
  web:
    image: nginx:latest
    container_name: nginx-php
    networks:
      - network-chur
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - "/dados/docker/environment/nginx/docker.sock:/tmp/docker.sock:ro"
      - "/dados/docker/environment/nginx/php-fpm/default.conf:/etc/nginx/conf.d/default.conf"
      - "/dados/docker/persistent/www/html:/var/www/html"
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm
    container_name: php-fpm
    networks:
      - network-chur
    volumes:
      - "/dados/docker/persistent/www/html:/var/www/html"

  myadmin:
    image: phpmyadmin:5.2.1-fpm
    container_name: phpmyadmin
    depends_on:
      - sgbd-mysql
    environment:
      - PMA_HOST = sgbd-mysql
    ports:
      - 8080:80
####### ZABBIX create Database ##########
  zabbix-mysql:
    container_name: mysql
    image: mysql:8.0.34
    depends_on:
      - sgbd-mysql
    networks:
      - network-chur
    env_file:
      - "/dados/docker/environment/mysql/zabbix/mysql.env"
    volumes:
      - "/dados/docker/persistent/mysql/data:/var/lib/mysql"
####### ZABBIX INFRA ##########
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql
    depends_on:
      - sgbd-mysql
      - zabbix-mysql
    networks:
      - network-chur
    links:
      - sgbd-mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - "/dados/docker/environment/zabbix/server/alertscripts:/usr/lib/zabbix/alertscripts"
      # /etc/zabbix/zabbix_server.conf
    env_file:
      - "/dados/docker/environment/mysql/zabbix/mysql.env"
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql
    networks:
      - network-chur
    links:
      - mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'

    depends_on:
      - mysql
   
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-chur
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql
      - zabbix-server
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2
    user: root
    networks:
      - network-chur
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    env_file:
      - "/dados/docker/environment/zabbix/agent/agent.conf"


############################################
networks:
  network-chur:
    driver: bridge
