#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM php:8.0-fpm
LABEL Aquiles Rodrigues <cyberfazer@gmail.com>

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

#
#--------------------------------------------------------------------------
# Software's Installation
#--------------------------------------------------------------------------
#
# Installing tools and PHP extentions using "apt", "docker-php", "pecl",
#

# Install "curl", "libmemcached-dev", "libpq-dev", "libjpeg-dev",
#         "libpng-dev", "libfreetype6-dev", "libssl-dev", "libmcrypt-dev",
RUN set -eux; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y --no-install-recommends \
            curl \
            zip \
            libmemcached-dev \
            libz-dev \
            libpq-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev \
            libssl-dev \
            libwebp-dev \
            libxpm-dev \
            libmcrypt-dev \
            libjpeg62-turbo-dev \
            zlib1g-dev \
            libzip-dev \
            libxml2-dev \
            libcurl3-dev \
            libonig-dev; \
    rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    apt-get install -y libmagickwand-dev; \
    pecl install imagick


RUN set -eux; \
    # Install the PHP pdo_mysql extention
    docker-php-ext-install pdo_mysql; \
    # Install the PHP pdo_pgsql extention
    docker-php-ext-install pdo_pgsql; \
    # Install the PHP other extention
    docker-php-ext-install mysqli; \ 
    docker-php-ext-install pdo; \
    docker-php-ext-install curl; \
    docker-php-ext-install mbstring; \
    docker-php-ext-install xml; \
    docker-php-ext-install json; \
    # Install the PHP gd library
    docker-php-ext-configure gd \
            --prefix=/usr \
            --with-jpeg \
            --with-webp \
            --with-xpm \
            --with-png \
            --with-zlib \
            --with-freetype; \
    docker-php-ext-install gd; \
    docker-php-ext-enable imagick mysqli pdo_mysql; \
    php -r 'var_dump(gd_info());'

EXPOSE 9000