FROM php:8.2-fpm 
LABEL Aquiles Rodrigues <cyberfazer@gmail.com>

RUN apt-get update 
RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev zlib1g-dev zip curl libcurl3-dev libzip-dev libonig-dev libxml2-dev \

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ 

# Installing additional PHP modules
RUN docker-php-ext-install gd \
    && docker-php-ext-install curl \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install pdo \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install xml \
    && docker-php-ext-install json

# Install and configure ImageMagick
RUN apt-get install -y libmagickwand-dev
RUN pecl install imagick

# Configure additional PHP modules
RUN docker-php-ext-enable imagick \
    && docker-php-ext-enable  mysqli \
    && docker-php-ext-enable  pdo_mysql

# Clean variable enviroment 
RUN apt-get purge -y libmagickwand-dev

# Install Composer so it's available
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN mkdir -p /usr/local/etc/php/teste.ok
RUN mkdir /tmp/teste.ok
    
ADD php.ini /usr/local/etc/php/

EXPOSE 9000








