version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8 \
      --collation-server=utf8_unicode_ci \
      --init-connect='SET NAMES UTF8;'
    networks:
      - network-cyberfazer
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/data
    env_file:
      - conexao.env

  # ==============================================================
  # --------------------------------------------------------------

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:6.2.6-ubuntu
    networks:
      - network-cyberfazer
    links:
      - mysql
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ssl:/etc/ssl/apache2
    env_file:
      - conexao.env

    depends_on:
      - mysql

volumes:
  ssl:
  data:
# ==============================================================
# --------------------------------------------------------------

networks:
  network-cyberfazer:
    driver: bridge
    ipam:
      driver: default
