version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8 \
      --collation-server=utf8_unicode_ci \
      --init-connect='SET NAMES UTF8;'
    networks:
      - network-cyberfazer
    ports:
      - "3306:3306"
    volumes:
      - "./zabbix/mysql:/var/lib/data"
    environment:
      - MYSQL_ROOT_PASSWORD=carryontech
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech

# ==============================================================
# --------------------------------------------------------------

 zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:6.0-ubuntu-latest
    networks:
      - network-cyberfazer
    links:
      - mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql

# ==============================================================
# --------------------------------------------------------------

networks:
  network-cyberfazer:
    driver: bridge
    ipam:
      driver: default
