# Utilizando sintax da versão 3:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: "3"

services:
  ###################################
  # Container proxy-reverse (Nginx)
  ###################################
  nginx-reverse:
    image: nginx:latest
    # jwilder/nginx-proxy
    hostname: nginx-reverse
    container_name: nginx-reverse_compose
    restart: always
    depends_on:
      - php-fpm
    networks:
      - bridge1
    #        extra_hosts:
    #            - "gitlab.chur.com.br:10.0.1.11"
    #            - "chur.com.br:10.0.1.10"
    ports:
      - 8080:80
      - 443:443
    volumes:
      # PASTAS LOCAIS PARA NGINX
      - "certificate-ssl:/etc/nginx/ssl"
      - "php-sites:/var/www/html"
      - "nginx-reverse_sites-enabled:/etc/nginx/sites-enabled"
      - "nginx-reverse_root:/root"
      - "nginx-reverse_NGINX_cache:/tmp/NGINX_cache"
      - "nginx-reverse_logs:/var/log/nginx"
      # - "nginx-reverse_conf.d:/etc/nginx/conf.d"
      # PASTA HTML_PHP ENTRE CONTAINERS
      - "php-sites:/var/www/html"
      # ARQUIVOS DE CONFIGURACAO PHP e CONFIG DEFAULT DO NGNIX
      - "/dados/docker/environment/php/php-logging.conf:/usr/local/etc/php-fpm.d/zz-log.conf"
      - "/dados/docker/environment/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
        # PASTA PUBLICA ENTRE CONTAINERS
      - "/var/docker/public:/public"
      - "/etc/localtime:/etc/localtime:ro"
      # --> nginx:latest ==
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # --> jwilder/nginx-proxy ==
      #- "/var/run/docker.sock:/tmp/docker.sock:ro"
      
    environment:
      #            - NGINX_HOST=xpaco.com.br
      - NGINX_PORT=80

  ###########################
  # Container PHP
  ###########################
  php-fpm:
    build: "/dados/docker/environment/php/"
    restart: always
    hostname: php-fpm
    container_name: php-fpm_compose
    networks:
      - bridge1
    expose:
      - 9000
    volumes:
      - "php-sites:/var/www/html"
      - "/dados/docker/environment/php/php-logging.conf:/usr/local/etc/php-fpm.d/zz-log.conf"
      - "/etc/localtime:/etc/localtime:ro"

  ###########################
  # Container   guacd
  ###########################
  #guacd:
  #  container_name: guacd_compose
  #  image: guacamole/guacd
  #  networks:
  #    guacnetwork_compose:
  #  restart: always
  #  volumes:
  #  - ./drive:/drive:rw
  #  - ./record:/record:rw

      
  #
  ###########################
  # Containers de banco de dados (MySQL)
  ###########################
  mysql:
    image: mysql:latest
    hostname: mysql
    container_name: mysql_compose
    restart: always
    networks:
      - bridge1
    ports:
      - "3306:3306"
    volumes:
      # Persistente
      - "mysql-data:/var/lib/mysql"
      # Ambiente
      - "mysql-conf-d:/etc/mysql/conf.d"
      - "/dados/docker/environment/mysql/my.cnf:/etc/mysql/my.cnf"
      - "/etc/localtime:/etc/localtime:ro"
      #     - dbsocket:/var/run/mysqld/
    env_file:
      - "/dados/docker/environment/mysql/tie-in.env"

volumes:
# CONFIGURACAO AMBIENTE
  mysql-conf-d:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/environment/mysql/conf.d'
  certificate-ssl:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/environment/ssl'
  nginx-reverse_sites-enabled:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/environment/nginx/sites-enabled'
  nginx-reverse_conf.d:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/environment/nginx/conf.d'
  # PERSISTENCIA DE DADOS
  php-sites:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/persistent/php/html'
  mysql-data:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/persistent/mysql/data'
  nginx-reverse_root:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/dados/docker/persistent/nginx/root"
  nginx-reverse_NGINX_cache:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/persistent/nginx/NGINX_cache'
  nginx-reverse_logs:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/dados/docker/persistent/nginx/logs'      

  docker-public:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /var/docker/public
    
networks:
  bridge1:
    driver: bridge
    ipam:
      driver: default