version: "3.7"

volumes:
  web:

services:
  web-apache:
           
    build: https://raw.githubusercontent.com/aquilesrodrigues/Docker/main/Dockerfiles/debian-Apache/Dockerfile
    container_name: web-apache_compose
    restart: always
    tty: true # Permitir interatividade com o container (-it)
    networks:
      - network-cyberfazer
    ports:
      - "80:80"
    volumes:
      - web:/var/www

# ==============================================================
# --------------------------------------------------------------

networks:
  network-cyberfazer:
    driver: bridge
    ipam:
      driver: default
# ==============================================================
# **************************************************************

