version: "3.7"

services:
  web:
    build: 
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN wget -c https://github.com/aquilesrodrigues/javascript-memory-game.git -O game-of-memory.tar
